site_name: Torrust Documentation
site_url: https://torrust.com/
site_author: Torrust Developers
site_description: Torrust Documentation

repo_name: torrust/torrust-documentation
repo_url: https://github.com/torrust/torrust-documentation

theme:
  palette:
    primary: blue
    scheme: slate
    accent: blue
  name: material

nav:
  - Introduction: index.md
  - 'Installation': installation.md
  - 'Torrust Tracker Usage':
    - Config: torrust-tracker/config.md
    - 'Tracking Modes': torrust-tracker/tracking_modes.md
    - API: torrust-tracker/api.md
  - 'Torrust Index Usage':
    - Config: torrust-index/config.md
    - API:
      - Overview: torrust-index/api.md
      - 'User': torrust-index/user_api.md
      - 'Torrent': torrust-index/torrent_api.md
      - 'Category': torrust-index/category_api.md

markdown_extensions:
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
