site_name: Torrust Documentation
site_url: https://torrust.com/
site_author: Torrust Developers
site_description: Torrust Documentation

repo_name: torrust/torrust-documentation
repo_url: https://github.com/torrust/torrust-documentation

theme:
  name: material
  font:
    text: Inter
  palette:
    scheme: torrust
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico

extra_css:
  - stylesheets/extra.css

nav:
  - Introduction: index.md
  - Tracker:
      - Installation: torrust-tracker/install.md
      - Usage: torrust-tracker/usage.md
      - Configuration: torrust-tracker/config.md
      - API: torrust-tracker/api.md
  - Index:
      - Installation: torrust-index/install.md
      - Configuration: torrust-index/config.md
      - API: torrust-index/api.md

markdown_extensions:
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
