site_name: Torrust Documentation
site_url: https://torrust.com/
site_author: Torrust Developers
site_description: Torrust Documentation

repo_name: torrust/torrust
repo_url: https://github.com/torrust/torrust

theme:
  palette:
    primary: blue
    scheme: slate
    accent: blue
  name: material

nav:
  - Introduction: index.md
  - 'Torrust Tracker':
      - Install: torrust-tracker/install.md
      - Config: torrust-tracker/config.md
      - API: torrust-tracker/api.md
  - 'Torrust Index':
      - Install: torrust-index/install.md
      - Config: torrust-index/config.md
      - API: torrust-index/api.md
  - 'Docker': https://github.com/torrust/torrust-docker

markdown_extensions:
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
