site_name: Torrust Documentation
site_url: https://torrust.com/
site_author: Torrust Developers
site_description: Torrust Documentation

repo_name: torrust/torrust-tracker
repo_url: https://github.com/torrust/torrust-tracker

theme:
  name: material
  font:
    text: Inter
  palette:
    scheme: torrust

extra_css:
  - stylesheets/extra.css

nav:
  - Introduction: index.md
  - 'Torrust Tracker':
      - Install: torrust-tracker/install.md
      - Config: torrust-tracker/config.md
      - API: torrust-tracker/api.md
  - 'Torrust Index':
      - Install: torrust-index/install.md
      - Config: torrust-index/config.md
      - API: torrust-index/api.md
  - 'Docker': https://github.com/torrust/torrust-docker

markdown_extensions:
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
